### ISSUE TITLE
Approval Reporting

### ISSUE THREAD

**Issue by mikeklop1979** [objectcomputing/check-ins#2540] opened 2024-07-08 15:50 UTC
Under Reviews, Check-Ins is currently reporting that the review process is 100% done and approved when the process just began. 

Check-Ins is somehow auto approving the process. 

Expected behavior:

The approval process should show the percent that is complete, not 100% right after the process starts.

**Comment by ocielliottc** [comment] 2024-09-26 16:39
I think this issue may have been overcome by events.  The review period is now displayed with the progress above the review period and no longer displays a percentage.

**Comment by mkimberlin** [comment] 2024-09-30 15:35
@ocielliottc This actually does still happen (the percentage display), but I think the issue is gone, so I'm going to close this.
![Screenshot 2024-09-30 at 10 34 42 AM](https://github.com/user-attachments/assets/d2919049-59ec-48ef-a3db-dd5b6e004c33)

**Closed by mkimberlin** 2024-09-30 15:35 UTC
